name: user
description: "App RM Febry for User"
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  timer_count_down: ^2.1.0
  provider: ^6.0.0
  intl: ^0.19.0
  http: ^1.2.2


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/logo/
    - assets/images/banner/
    - assets/images/menu/drink/
    - assets/images/menu/other/
    - assets/images/menu/package/
    - assets/images/menu/sidedish/
    - assets/images/payments/va/
    - assets/images/payments/other/